# Generated by Django 6.0 on 2025-12-14 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0002_categoriatransacao_transacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
            ],
            options={
                'verbose_name': 'Despesa / Saída',
                'verbose_name_plural': 'Despesas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_pdv.transacao',),
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
            ],
            options={
                'verbose_name': 'Receita / Entrada',
                'verbose_name_plural': 'Receitas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_pdv.transacao',),
        ),
    ]
