# Generated by Django 6.0 on 2025-12-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0005_venda_eh_entrega_venda_endereco_entrega_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemestoque',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='venda',
            name='conferencia_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='troco_para',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
