# Generated by Django 6.0 on 2025-12-27 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0006_alter_itemestoque_options_venda_conferencia_ok_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Obs do Pedido'),
        ),
        migrations.AddField(
            model_name='venda',
            name='origem',
            field=models.CharField(choices=[('PDV', 'Balcão/Caixa'), ('APP', 'App Cliente')], default='PDV', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_pdv.venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_pdv.loja'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Em Aberto (Balcão)'), ('FINALIZADO', 'Finalizado'), ('ORCAMENTO', 'Orçamento'), ('PENDENTE', 'Aguardando Aprovação'), ('EM_PREPARACAO', 'Em Separação'), ('SAIU_ENTREGA', 'Saiu para Entrega'), ('CANCELADO', 'Cancelado/Recusado')], default='ABERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
