# Generated by Django 6.0 on 2025-12-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0007_venda_observacao_venda_origem_alter_itemvenda_venda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='taxa_entrega_app',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Taxa de Entrega (App)'),
        ),
    ]
