# Generated by Django 6.0 on 2025-12-30 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0008_loja_taxa_entrega_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriatransacao',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_pdv.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_pdv.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_pdv.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_pdv.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_pdv.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Loja Ativa?'),
        ),
        migrations.AddField(
            model_name='loja',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moto',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_pdv.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motoboy',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_pdv.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Disponível no App?'),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_pdv.loja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome do Item'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='gerente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lojas_gerenciadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moto',
            name='placa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_pdv.loja'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='itemestoque',
            unique_together={('loja', 'nome')},
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_pdv.loja')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]