# Generated by Django 6.0 on 2026-01-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0010_motoboy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='loja_aberta',
            field=models.BooleanField(default=True, verbose_name='Loja Aberta para Delivery'),
        ),
    ]
