# Generated by Django 6.0 on 2026-01-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0011_loja_loja_aberta'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='data_hora_abertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='data_hora_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
