# Generated by Django 6.0 on 2026-01-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0012_caixa_data_hora_abertura_caixa_data_hora_fechamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='taxa_entrega_pdv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa Padrão (PDV)'),
        ),
    ]
