# Generated by Django 6.0 on 2026-01-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0013_loja_taxa_entrega_pdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Em Aberto (Balcão)'), ('FINALIZADO', 'Finalizado'), ('ORCAMENTO', 'Orçamento'), ('PENDENTE', 'Aguardando Aprovação'), ('EM_PREPARACAO', 'Em Separação'), ('SAIU_ENTREGA', 'Saiu para Entrega'), ('CANCELADO', 'Cancelado/Recusado'), ('AGUARDANDO_FINALIZAR', 'Pausado / Finalizar Depois')], default='ABERTO', max_length=20),
        ),
    ]
