# Generated by Django 6.0 on 2026-01-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0014_alter_venda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data limite para o próximo pagamento', null=True, verbose_name='Vencimento da Mensalidade'),
        ),
        migrations.AddField(
            model_name='loja',
            name='link_pagamento_atual',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Boleto/Pix'),
        ),
        migrations.AddField(
            model_name='loja',
            name='status_assinatura',
            field=models.CharField(choices=[('ATIVO', 'Ativo - Acesso Liberado'), ('BLOQUEADO', 'Bloqueado - Pagamento Pendente'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20, verbose_name='Status da Assinatura'),
        ),
        migrations.AddField(
            model_name='loja',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=99.9, max_digits=10, verbose_name='Valor da Mensalidade'),
        ),
    ]
