# Generated by Django 6.0 on 2026-01-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0015_loja_data_vencimento_loja_link_pagamento_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='dias_tolerancia',
            field=models.IntegerField(default=3, help_text='Quantos dias a loja pode usar após o vencimento antes de bloquear total.'),
        ),
        migrations.AddField(
            model_name='loja',
            name='ultimo_acesso',
            field=models.DateTimeField(blank=True, help_text='Data e hora da última interação de qualquer usuário desta loja.', null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='status_assinatura',
            field=models.CharField(choices=[('ATIVO', 'Ativo - Acesso Liberado'), ('BLOQUEADO', 'Bloqueado - Pagamento Pendente'), ('CANCELADO', 'Cancelado'), ('GRATUITO', 'Período de Teste / Gratuito')], default='ATIVO', max_length=20, verbose_name='Status da Assinatura'),
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('comprovante_url', models.URLField(blank=True, help_text='Link do comprovante ou PDF', null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='app_pdv.loja')),
            ],
        ),
    ]
