# Generated by Django 6.0 on 2026-03-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0016_loja_dias_tolerancia_loja_ultimo_acesso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade (Peça, Fardo, Saco Fechado)'), ('KG', 'Quilograma / Granel (KG)'), ('L', 'Litros (L)')], default='UN', max_length=2, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='quantidade_estoque',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_baixa',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10, verbose_name='Qtd retirada do estoque (ex: 12 p/ Pack, 1.5 p/ KG)'),
        ),
    ]
