# Generated by Django 6.0 on 2026-03-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0018_venda_quem_recebeu'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='perm_caixa',
            field=models.BooleanField(default=False, verbose_name='Gerenciar Caixa'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='perm_estoque',
            field=models.BooleanField(default=False, verbose_name='Modificar Estoque/Produtos'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='perm_pdv',
            field=models.BooleanField(default=True, verbose_name='Acessar PDV (Vender)'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='perm_relatorios',
            field=models.BooleanField(default=False, verbose_name='Ver Relatórios'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='perm_torre',
            field=models.BooleanField(default=False, verbose_name='Torre de Controle'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='perm_usuarios',
            field=models.BooleanField(default=False, verbose_name='Gerenciar Usuários'),
        ),
    ]
