# Generated by Django 6.0 on 2026-03-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0019_perfilusuario_perm_caixa_perfilusuario_perm_estoque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='perm_dashboard',
            field=models.BooleanField(default=False, verbose_name='Acessar Dashboard (Faturamento)'),
        ),
    ]
