# Generated by Django 6.0 on 2026-03-06 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0020_perfilusuario_perm_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro (Caixa)'), ('PIX', 'Pix'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito')], default='DINHEIRO', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Lançamento'),
        ),
    ]
