# Generated by Django 6.0 on 2026-03-06 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0021_transacao_forma_pagamento_alter_transacao_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_caixa', to='app_pdv.caixa'),
        ),
    ]
