# Generated by Django 6.0 on 2026-03-10 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0022_transacao_caixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Rede/Franquia (Ex: The King)')),
                ('slug', models.SlugField(help_text='Nome para o link (ex: the-king)', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='redes/')),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='loja',
            name='nome_unidade',
            field=models.CharField(blank=True, help_text='Nome da filial para o cliente clicar. Ex: Botânico, Metrópoles', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='app_pdv.rede'),
        ),
    ]
