# Generated by Django 6.0 on 2026-03-17 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0024_produto_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTransferenciaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nome', models.CharField(max_length=150, verbose_name='Item Transferido')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('loja_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recebidas', to='app_pdv.loja')),
                ('loja_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='app_pdv.loja')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Log de Transferência',
                'verbose_name_plural': 'Logs de Transferência',
                'ordering': ['-data_transferencia'],
            },
        ),
    ]
