# Generated by Django 6.0 on 2026-03-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0025_logtransferenciaestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lote / Observação'),
        ),
    ]
