# Generated by Django 6.0 on 2026-03-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0026_itemestoque_data_validade_itemestoque_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='usa_moveon',
            field=models.BooleanField(default=False, verbose_name='Utilizar frota terceirizada (MoveON)'),
        ),
    ]
