# Generated by Django 6.0 on 2026-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0032_custo_multi_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de Lançamento'),
        ),
    ]
