# Generated by Django 5.1.7 on 2026-06-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0039_loja_estoque_diario_log_fechamento'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logfechamentoestoquediario',
            new_name='app_pdv_log_loja_id_ce16db_idx',
            old_name='app_pdv_log_loja_dat_tipo_idx',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pontos_fidelidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pontos de fidelidade acumulados'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='progresso_fidelidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Progresso até próxima promoção'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='promocao_fidelidade_ativa',
            field=models.BooleanField(default=False, verbose_name='Promoção de fidelidade disponível?'),
        ),
        migrations.AddField(
            model_name='loja',
            name='campanha_desconto_pct',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Desconto sugerido nas campanhas (%)'),
        ),
        migrations.AddField(
            model_name='loja',
            name='fidelidade_ativa',
            field=models.BooleanField(default=False, verbose_name='Ativar plano de fidelidade?'),
        ),
        migrations.AddField(
            model_name='loja',
            name='fidelidade_desconto_pct',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Desconto da promoção (%)'),
        ),
        migrations.AddField(
            model_name='loja',
            name='fidelidade_meta',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Meta para ativar promoção (qtd produtos ou pontos)'),
        ),
        migrations.AddField(
            model_name='loja',
            name='fidelidade_tipo_meta',
            field=models.CharField(choices=[('PRODUTOS', 'Por quantidade de produtos'), ('PONTOS', 'Por valor acumulado (pontos)')], default='PRODUTOS', max_length=20, verbose_name='Tipo de meta da promoção'),
        ),
        migrations.AddField(
            model_name='loja',
            name='msg_campanha_ativos',
            field=models.TextField(blank=True, default='', help_text='Placeholders: {cliente}, {bairro}, {desconto}', verbose_name='Mensagem para clientes ativos (30 dias)'),
        ),
        migrations.AddField(
            model_name='loja',
            name='msg_campanha_inativos',
            field=models.TextField(blank=True, default='', verbose_name='Mensagem para clientes inativos (60+ dias)'),
        ),
        migrations.AddField(
            model_name='loja',
            name='whatsapp_msg_entrega_concluida',
            field=models.TextField(blank=True, default='Olá {cliente}! Seu pedido #{pedido} foi entregue. Obrigado pela preferência!', verbose_name='Mensagem — entrega concluída (cliente)'),
        ),
        migrations.AddField(
            model_name='loja',
            name='whatsapp_msg_novo_pedido',
            field=models.TextField(blank=True, default='', help_text='Placeholders: {pedido}, {cliente}, {telefone}, {whatsapp}, {endereco}, {pagamento}, {itens}, {total}, {obs}', verbose_name='Mensagem automática — novo pedido (empresa)'),
        ),
        migrations.AddField(
            model_name='loja',
            name='whatsapp_msg_saiu_entrega',
            field=models.TextField(blank=True, default='Olá {cliente}! Seu pedido #{pedido} saiu para entrega. Em breve chegaremos!', verbose_name='Mensagem — motoboy saiu para entrega (cliente)'),
        ),
        migrations.AddField(
            model_name='loja',
            name='whatsapp_notificar_pedido',
            field=models.BooleanField(default=False, verbose_name='Notificar WhatsApp da empresa em novos pedidos?'),
        ),
        migrations.AddField(
            model_name='loja',
            name='whatsapp_numero_empresa',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp da empresa (novos pedidos)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='dias_recompra',
            field=models.IntegerField(blank=True, help_text='Ex.: 5 para água, 30 para gás. Deixe vazio para não rastrear.', null=True, verbose_name='Dias sem compra para alerta'),
        ),
        migrations.AddField(
            model_name='produto',
            name='mensagem_recompra',
            field=models.TextField(blank=True, default='Olá {cliente}, sua {produto} está acabando. Gostaria de fazer um novo pedido?', help_text='Placeholders: {cliente}, {produto}, {dias}', verbose_name='Mensagem WhatsApp de recompra'),
        ),
        migrations.AddField(
            model_name='produto',
            name='rastrear_recompra',
            field=models.BooleanField(default=False, help_text='Exibe alerta no dashboard quando o cliente passar dos dias configurados sem comprar.', verbose_name='Rastrear recompra deste produto?'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categoriatransacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formapagamentoloja',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logtransferenciaestoque',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='controla_vasilhame_vazio',
            field=models.BooleanField(default=False, help_text="Ao vender, incrementa vasilhame vazio do item. Na entrada de estoque, consome vazios ao reabastecer. Exibe coluna 'Vazio' em /estoque/.", verbose_name='Controle de botijões/galões vazios?'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='estoque_diario',
            field=models.BooleanField(default=False, help_text="Permite editar cheios/vazios em /estoque/, registra abertura/fechamento do dia e usa esses saldos no PDV. Requer 'Controle de botijões/galões vazios' ativo.", verbose_name='Estoque diário (contagem manual)?'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='motoboy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pagamentofiado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='precofornecedoritem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rede',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
