# Generated by Django 5.1.7 on 2026-07-02 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0042_seguranca_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='venda_completa',
            field=models.BooleanField(default=False, verbose_name='Venda completa (sem troca de vasilhame)'),
        ),
        migrations.AddField(
            model_name='loja',
            name='permite_venda_completa',
            field=models.BooleanField(default=False, help_text='Depósitos: cliente sem vazio pode comprar produto cheio sem troca de vasilhame.', verbose_name='Permitir venda de produto completo (gás+vasilhame)?'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_venda_completo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Se vazio, usa preço cheio + produto vazio do mesmo item.', max_digits=10, null=True, verbose_name='Preço venda completa (cheio+vasilhame)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='desconto_fidelidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto fidelidade aplicado'),
        ),
        migrations.AddField(
            model_name='venda',
            name='eh_cortesia',
            field=models.BooleanField(default=False, verbose_name='Venda Cortesia?'),
        ),
        migrations.AlterField(
            model_name='liquidacaovenda',
            name='meio_liquidacao',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('CORTESIA', 'Cortesia')], default='DINHEIRO', max_length=20, verbose_name='Meio de liquidação'),
        ),
        migrations.AlterField(
            model_name='pagamentofiado',
            name='meio_liquidacao',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('CORTESIA', 'Cortesia')], default='DINHEIRO', max_length=20, verbose_name='Meio de liquidação'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='meio_liquidacao',
            field=models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('CORTESIA', 'Cortesia'), ('MISTO', 'Pagamento Dividido')], max_length=20, null=True, verbose_name='Meio de Liquidação'),
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAR', 'Criou'), ('EDITAR', 'Editou'), ('EXCLUIR', 'Excluiu'), ('LOGIN', 'Login'), ('TRANSFERIR', 'Transferiu estoque'), ('VENDA', 'Venda'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('modelo', models.CharField(blank=True, default='', max_length=80)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_pdv.loja')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
