# Generated by Django 5.1.7 on 2026-07-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0043_melhorias_pdv_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='usa_venda_completa',
            field=models.BooleanField(default=False, help_text='Baixa apenas estoque cheio, sem incrementar vazios. Use preço venda completa abaixo.', verbose_name='Venda completa (gás + vasilhame, sem troca)?'),
        ),
    ]
