# Generated by Django 6.0 on 2026-03-19 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_motorista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=100)),
                ('cliente_whatsapp', models.CharField(max_length=20)),
                ('origem_texto', models.CharField(max_length=255)),
                ('destino_texto', models.CharField(max_length=255)),
                ('origem_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('origem_long', models.CharField(blank=True, max_length=50, null=True)),
                ('destino_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('destino_long', models.CharField(blank=True, max_length=50, null=True)),
                ('distancia_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tempo_estimado_minutos', models.IntegerField(default=0)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('ACEITO', 'Aceito'), ('EM_ROTA', 'Motorista a Caminho'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_agendamento', models.DateTimeField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas', to='transporte.motorista')),
            ],
        ),
    ]
