# Generated by Django 6.0 on 2026-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_corrida_venda_pdv_id_alter_corrida_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrida',
            name='cliente_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
